name: Test REUSE compliance

on:
  push:
    branches:
    - master
    pull_request:
      branches: '**'

jobs:
  reuse:
    name: Test REUSE compliance
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run `reuse lint`
      uses: fsfe/reuse-action@v1
