name: Test Go code

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:
  test:
    name: Test Go code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Initialise Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Run `go test`
        run: go test -v ./...
